# Generated by Django 4.2.11 on 2024-03-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_auto_20181020_0450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
